### ISSUE TITLE
Interaction 2 error in Origami Live For IOS

### ISSUE THREAD

**Issue by kimseongrim** [facebookarchive/origami#68]
In the OSX is good，But in the Origami Live For IOS Tap ANY WHERE stir.
<img width="1278" alt="screen shot 2016-05-16 at 3 03 00 pm" src="https://cloud.githubusercontent.com/assets/6750397/15282664/53a04aa6-1b77-11e6-9367-ba64fabb2b98.png">

**Comment by kimseongrim** [comment]
Upload err DEMO
[Tap err.qtz.zip](https://github.com/facebook/origami/files/265799/Tap.err.qtz.zip)

**Comment by tarngerine** [comment]
cc @bwalkin is this related to the regression? i can repro

**Comment by lilllli** [comment]
Encountering the same issue. Has this been looked into?

**Comment by tarngerine** [comment]
As Origami Studio is coming out soon we have suspended work on this. The code is open source in this repo. 






On Tue, Oct 11, 2016 at 11:22 AM -0400, "Lillian Chen" <notifications@github.com> wrote:












Encountering the same issue. Has this been looked into?
